spring:
    #profiles.active: production
    profiles.active: hbase
localFilePath: /home/hbase/data
hdfsFilePath: /hbase-data
hdfsUrl: hdfs://node2.gh.swc.hdp:8020 # hdfs://node2.gh.swc.hdp:8020   192.168.1.3:9000